# -*- coding: utf-8 -*-
"""Projeto Celsius Fahrenheit.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKPbI8pEz_P8j08P08_VJWlzLJDuyaBL

Equação de Conversão T(ºF) = T(ºC) x 9/5 + 32
"""

import tensorflow as tf
tf.__version__

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

temperature_df = pd.read_csv('/content/Celsius-to-Fahrenheit.csv')
temperature_df.reset_index(drop = True, inplace = True)

temperature_df

sns.scatterplot(x=temperature_df['Celsius'], y=temperature_df['Fahrenheit'])

X_train = temperature_df['Celsius']
y_train = temperature_df['Fahrenheit']

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units = 1, input_shape = [1]))
model.summary()

model.compile(optimizer=tf.keras.optimizers.Adam(0.1), loss = 'mean_squared_error')

epochs_hist = model.fit(X_train, y_train, epochs = 500)

epochs_hist.history.keys()

plt.plot(epochs_hist.history['loss'])
plt.title('Model Loss Progress During Training')
plt.xlabel('Epoch')
plt.ylabel('Training loss')
plt.legend(['Training loss']);

model.get_weights()

temp_c = 10
temp_f = model.predict(np.array([temp_c]))
temp_f

temp_f1 = 9/5 * temp_c + 32
temp_f1